### ISSUE TITLE
The environment name on "environment-file" is not defined, using "enviroment-activate"!

### ISSUE THREAD

**Issue by tdegeus** [conda-incubator/setup-miniconda#104]
How should I deal with this warning:
```
The environment name on "environment-file" is not defined, using "enviroment-activate"!
```

FYI:
```yaml
    - name: Set conda environment "test"
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: environment.yaml
        activate-environment: test
        auto-activate-base: false
```

A second question is if I should modify to get rid of

```
Warning: 'defaults' already in 'channels' list, moving to the top
```
