### ISSUE TITLE
Can we add some documentation that the default env name is `test`?

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-incubator/setup-miniconda#110]
This would prevent failures in the default case when assuming this is the same as installing miniconda and activating it using say
```conda activate base```

**Comment by goanpeca** [comment]
Thanks for the report @mariusvniekerk, and yes absolutely!

On the bottom less to do bucket list 😆.

For context, any particular instance where thigs happened that were not expected? Just to gather information on the use cases.

**Comment by mariusvniekerk** [comment]
conda-lock's test suite installs some thing using pip

```
conda install pip pytest
conda activate base
# the pip here is actually /usr/bin/pip now
# and this fails
pip install ensureconda
```

**Comment by goanpeca** [comment]
Got it! 

So basically `conda activate base` is the culprit in that setup. We "encourage" the use of envs different than `base` on this action, there may be cases where using base makes sense, so the auto activate base plus an empty activate environment accomplish this in this case.

Will add the extra information more prominently on the README.

Thanks for the feedback!

**Comment by goanpeca** [comment]
Some reference information

@mariusvniekerk we do this by default for you: so you can have cases:

Either you use `base` by default, in which case you need

## Activate `base` for all steps

```yaml
 - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true	
          activate-environment: ""
          channels: conda-forge
```

## Activate `base` and then `whatever` for all steps

```yaml
 - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
          activate-environment: whatever
          channels: conda-forge
```


## Activate `base` and then `test` for all steps

```yaml
 - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
          channels: conda-forge
```


So in short you do not need to activate `test` we do that for you (as a convenience based on `activate-environment`)
