### ISSUE TITLE
Error: Bundled Miniconda not found!

### ISSUE THREAD

**Issue by edgarriba** [conda-incubator/setup-miniconda#113]
hi! congrats for this package - it's really helpful.

we are using it in [`kornia`](https://github.com/arraiyopensource/kornia) for building our CI pipeline and we are facing some issues with the setup for a self-hosted device.

In particular we have the following error:

![image](https://user-images.githubusercontent.com/5157099/100115420-c8815280-2e72-11eb-8521-9d66c6cec966.png)
https://github.com/kornia/kornia/runs/1448438566?check_suite_focus=true

The `.yml` used to define this workflow can be found here:
https://github.com/kornia/kornia/blob/master/.github/workflows/tests_cuda.yml

Thanks in advance,

**Comment by goanpeca** [comment]
Hi @edgarriba, thanks for the kind words and the report :) 

So Github runners come with a bundled miniconda already installed on different locations (depending on the OS system) so your self hosted runners should have a miniconda available at the `$CONDA` environment variable.

In the meantime you could define an specific version of miniconda to use to force the download and install of miniconda (will take a bit longer, but it should solve the issue)

Something like:

```yaml
        with:
          miniconda-version: "latest"
```

Could you please check?

---

This is a very specific use case, but maybe we could check for existence and then download if not found what do you @conda-incubator/setup-miniconda-team think?

**Comment by jaimergp** [comment]
Not sure about the automated download. Which one would we default to? `latest`? Or should we try to provide the [same as bundled](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#package-management)? 

The safest thing would be error + suggestion, I think? Like:

> "Oops, $CONDA does not exist! Is this a self-hosted runner? You might want to use `miniconda-version: "latest"` option to automatically download and install latest one."

**Comment by edgarriba** [comment]
@goanpeca worked like a charm - thanks so much for the help :)

**Comment by goanpeca** [comment]
Glad to be of help @edgarriba.

Will open just to continue the discussion of what could be a good option for these cases :)

**Comment by goanpeca** [comment]
>Not sure about the automated download. Which one would we default to? latest? Or should we try to provide the same as bundled?

Good question... I guess we could raise a warning, like, 

>Bundled CONDA not found, downloading latest miniconda, if you want an specific version of miniconda, please use the `miniconda-version: ...` key.

**Comment by goanpeca** [comment]
Wanna work on this one @jaimergp :) ?

**Comment by jaimergp** [comment]
Sure. I'll wait until #107 et al are merged though!

**Comment by kengz** [comment]
I encountered the same problem, and fixed it by supplying the `CONDA` env var, though I'd share. So part of the actions yaml looks like:
```yaml
      ...
      - name: Setup Conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /home/your_name/miniconda3
        with:
          activate-environment: your_conda
          environment-file: environment.yml
          python-version: 3.9.1
          auto-activate-base: false
      ...
```
