### ISSUE TITLE
updating conda env fails with file not found 

### ISSUE THREAD

**Issue by sam-hoffman** [conda-incubator/setup-miniconda#117]
I'm following the caching example and it's consistently failing when looking for the environment.yml file. It seems to expand the path to the file twice, even though I'm not explicitly expanding the path?

Specifically, the error is: 
```
Error: ENOENT: no such file or directory, open '/home/runner/work/myrepo/myrepo/home/runner/work/myrepo/myrepo/myfolder/env.yml'
```

The action looks like this: 
```
name: test-on-pr

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if env.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('myfolder/env.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          channel-priority: strict
          environment-file: myfolder/env.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('myfolder/env.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file myfolder/env.yml --name base
      - name: Test with pytest
        run: |
          pytest myfolder/tests
```

Thanks in advance for your help!
