### ISSUE TITLE
Is the "channels" warning an issue?

### ISSUE THREAD

**Issue by jGaboardi** [conda-incubator/setup-miniconda#132]
**issue:**

```
"channels" set on the "environment-file" do not match "channels" set on the action!
```

I am getting [the above warning](https://github.com/jGaboardi/tigernet/actions/runs/444805834), which seems to be thrown regardless of OS/Python version, ([Ubunutu/3.7](https://github.com/jGaboardi/tigernet/runs/1609915459?check_suite_focus=true#step:4:192), for example). The workflow runs without failing so it doesn't appear to be a problem, but I am wondering if I doing something incorrectly or something could be more streamlined. Unless I am mistaken (which could absolutely be the case), the name of the only channel I am using (`conda-forge`) is exactly the same in the workflow file and the environment file.

**associated files:**
* [workflow `.yml`](https://github.com/jGaboardi/tigernet/blob/main/.github/workflows/unittests.yml#L36)
* [example environment file](https://github.com/jGaboardi/tigernet/blob/main/ci/39.yaml#L3) and [CI directory](https://github.com/jGaboardi/tigernet/tree/main/ci)
* [actions run logs](https://github.com/jGaboardi/tigernet/actions/runs/444805834)

**Comment by goanpeca** [comment]
Hi @jGaboardi, thanks for the report.

That is indeed unexpected. We will check!

**Comment by jGaboardi** [comment]
> Hi @jGaboardi, thanks for the report.
> 
> That is indeed unexpected. We will check!

Super, thanks!

**Comment by bollwyvl** [comment]
I may have added that to the ignored warnings...

**Comment by bnavigator** [comment]
Any news on this? I see the same.

workflow:
```yaml
- name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        if: matrix.distribution == 'conda'
        with:
          channels: conda-forge
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          activate-environment: test-env
          environment-file: ./Slycot/.github/conda-env/test-env.yml
          auto-activate-base: false
```

test-env.yml
```yaml
channels:
  - conda-forge
```
