### ISSUE TITLE
anaconda: command not found

### ISSUE THREAD

**Issue by nanthony21** [conda-incubator/setup-miniconda#141]
I am trying to use the `anaconda upload` command to upload my conda package to my channel. Even though I install `anaconda-client`, when I try to call `anaconda` I get `command not found`. A simplified yaml is below.
```
name: Upload Anaconda Cloud

on: workflow_dispatch
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
         auto-activate-base: true
         activate-environment: ""
      - name: Install dependencies
        run: conda install anaconda-client 
      - name: test anaconda
        run: anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload condaDist/noarch/mypackage*
```

Here is the error that I get.
```
Run anaconda upload condaDist/noarch/mypackage*
/home/runner/work/_temp/e7279193-c644-4b95-9764-e6e2c988ef20.sh: line 1: anaconda: command not found
```

Does anyone know why I'm not able to use anaconda-client even though it has been installed?

**Comment by bollwyvl** [comment]
Likely, your [shell isn't activated properly](https://github.com/conda-incubator/setup-miniconda/tree/v2.0.1#IMPORTANT)... annoying, but not much we can do, at present, to robustly handle `pre-activate` scripts, etc.

**Comment by nanthony21** [comment]
Hmm, I think you're right.

I changed my example script to this:

```
name: Upload Anaconda Cloud

on: workflow_dispatch
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Install dependencies
        shell: bash -l {0}
        run: |
            conda install anaconda-client 
            anaconda upload condaDist/noarch/mypackage*
```

Github's online yaml parser says that `bash -l {0}` is an invalid value. If I try to run it I get this error with no further information at the start of that step.

```
Error: Process completed with exit code 1.
```
