### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by chrisjbillington** [conda-incubator/setup-miniconda#143]
Thanks for the great project!

Miniconda has x86 (i.e. 32-bit) installers for Windows and Linux, and I currently use github actions to build both 32-bit and 64-bit packages for Windows. My current workflows are not using `setup-miniconda`, but `setup-miniconda` seems to solve some issues I was having and I'd like to switch my workflows to use it.

So something I'm missing is being able to pass in an `architecture` configuration option to `setup-miniconda` that would download for example `Miniconda3-latest-Windows-x86.exe` instead of `Miniconda3-latest-Windows-x86_64.exe` if x86 were specified. x86_64 should continue to be the default, and x86 should be an error on `macos` since no such thing exists.

With my current workflows I download and install miniconda somewhat manually, and this works fine - literally the only difference is downloading the x86 installer instead of the x86_64 one.

**Comment by chrisjbillington** [comment]
My mistake, I see this is already supported:

```yaml
  architecture:
    description:
      'Architecture of Miniconda that should be installed. Available options on
      GitHub-hosted runners are "x86" and "x64". Default is "x64".'
    required: false
    default: "x64"
```

Which is excellent, thanks again!
