### ISSUE TITLE
Consider making the default Python version the same as the base environment's Python version

### ISSUE THREAD

**Issue by chrisjbillington** [conda-incubator/setup-miniconda#144]
I'm using `setup-miniconda` for a part of my workflow with default settings:

```yaml
- name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
```

At the moment this gets me a Python 3.9 environment. Unfortunately I'm encountering bugs with anaconda tools under 3.9, for example Anaconda-Platform/anaconda-client#555 which makes my packages fail to upload to anaconda cloud at the end of the workflow.

The bug in `anaconda-client` is obviously not `setup-miniconda`'s fault, but issues like this seem common when a new version of Python is out, and conda/Anaconda moves somewhat slowly, supporting the new Python version but not using them by default. It's also the case that many packages aren't available when a new Python is out. 

The current default base environment if you download the latest miniconda is Python 3.8, not 3.9. I think this version is a good idea of what the Anaconda project thinks is the latest version you should use subject to sufficient stability and package availability, and until they are shipping 3.9 in the default base environment, it should be considered somewhat 'bleeding edge'.

I propose when the Python version is not specified, `setup-miniconda` use whatever version the latest Miniconda is currently shipping in the default base environment, rather than the latest that conda technically allows.

As a workaround I'm just using the base environment when I want to use whatever Python miniconda is shipping by default:
```
- name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
```

**Comment by bollwyvl** [comment]
Welp, always-update-everything is kind of the conda way, irrespective of what a7a thinks... and python is not the only game in town. In light of that, It seems like:

- your workaround
- specifying `python-version: 3.8` and letting it build and activate a `test` env,  as updating `base` can create it's own problems
- specifying `environment-file: .github/environment.yml`

...aren't _too_ odious a bunch of options, and don't leave you as much to the whims of github, conda, a7a, conda-forge, or this action, to decide for you. 

@conda-incubator/setup-miniconda-team thoughts?

**Comment by chrisjbillington** [comment]
For clarification: miniconda does have installers with a 3.9 base environment available, but the download link on [the main download page](https://docs.conda.io/en/latest/miniconda.html) is for 3.8, and the `Miniconda3-latest-*.{sh,exe}` [downloads](https://repo.anaconda.com/miniconda/) have 3.8.5 as the base environment. So that's the sense in which 3.8 is currently the recommended version from the conda project.

Manually specifying 3.8 works, but I'll have to ensure to update it at the appropriate times. Using the base environment means I'm kept more-or-less up to date with a well-supported Python version without the workflow bit-rotting. I was unaware that updating the base environment can cause issues, so perhaps using base isn't a good idea. Maybe I'll curl the download page to figure out the version before running `setup-miniconda` :p. Or have `setup-miniconda` activate base, inspect the Python version, and use that to create an environment.

> don't leave you as much to the whims of github, conda, a7a, conda-forge,

Well, the whims of which version they recommend by default is quite useful. I've been spending way too much time maintaining workflows that are supposed to be saving me time lately, so I'm pretty averse to pinning versions, which implies I need to make a conscious decision when to bump that version later (i.e. more work for me).

**Comment by jaimergp** [comment]
I usually leave `base` untouched (auto update = False) so it still uses what the installer shipped, which I assume it was well tested. I make sure the installer is recent (I prefer the Miniforge distribution for these cases). Then I set my environment file with the dependencies I want, so they can update freely within the imposed restraints (if any). 

Note that I normally test against a matrix of versions, so I am kind of manually specifying the Python versions, so this advice might not apply to your case.

So basically you are asking for an option `python-version: same-as-distribution` (or `same-as-installer`, `same-as-shipped`, you name it). A workaround might be a preprocessing step, where you compute the shipped Python version on your own set an output that you will apply then in the `python-version` field of `setup-miniconda`.

```yaml
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compute shipped Python in Conda
        id: shipped_python
        run: |
          # this for local conda
          pyver=$($CONDA/bin/python -V)
          # this other for Anaconda's default
          # 1. download and parse index from https://repo.anaconda.com/miniconda/
          # 2. retrieve the hash for `*latest*`
          # 3. find the same hash in a `*py3x*` filename, since latest it's just a renamed copy
          # 4. that filename contains your python version $pyver
          echo "::set-output name=version::$pyver"

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ steps.shipped_python.outputs.version }}
          auto-activate-base: true
```

You'll have to address platforms differences and so on, so maybe it makes sense to write a little Python script for the `shipped_python` step.
