### ISSUE TITLE
Cannot find conda-installed binaries with caching example

### ISSUE THREAD

**Issue by edmundsj** [conda-incubator/setup-miniconda#150]
I followed the instructions in the "caching" example on the github marketplace setting ``path: ~/conda_pkgs_dir``. I am subsequently using several of the binaries installed this way (flake8, pytest) in subsequent actions. However, when I try to run those steps, they cannot find the binaries! I would expect the binaries to be located in ``$CONDA_PKGS_DIR/bin/binary_name`` (i.e. ``$CONDA_PKGS_DIR/bin/flake8``), but this does not appear to be the case. What am I doing wrong? Are the binaries installed elsewhere? I also tried the ``$CONDA_PKGS_DIR/flake8`` path and ``~/conda_pkgs_dir/bin/flake8`` directly in other builds, but no matter what I try the binaries cannot be found. Where are they? How do I run them?

Repository is here: https://github.com/edmundsj/template
Failing build referenced is 50: https://github.com/edmundsj/template/runs/2047384519?check_suite_focus=true

Output from github actions build server:
```
Run ~/conda_pkgs_dir/bin/pytest --cov=./source --cov-report xml
  ~/conda_pkgs_dir/bin/pytest --cov=./source --cov-report xml
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
/home/runner/work/_temp/088f2f47-1684-4bd7-b2f0-2cef5a3faab0.sh: line 1: /home/runner/conda_pkgs_dir/bin/pytest: No such file or directory
Error: Process completed with exit code 127.
```

Full workflows file:
```
name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}
    - name: Setup conda, install dependencies
       uses: conda-incubator/setup-miniconda@v2
       with:
         activate-environment: anaconda-client-env
         channel-priority: strict
         environment-file: environment.yml
         use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
 
    - name: Test with pytest using full test suite
      run: |
        $CONDA_PKGS_DIR/bin/pytest --cov=./source --cov-report xml
     - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        $CONDA_PKGS_DIR/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars         wide
        $CONDA_PKGS_DIR/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

```

and my environment.yml:

```
name: anaconda-client-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - flake8
  - coverage
  - pytest
  - pytest-cov
  - coveralls
  - matplotlib
  - numpy
  - pandas
  - pip:
    - sphinxcontrib-bibtex
  - pyserial
  - pyvisa
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-jsmath
  - setuptools
  - wheel
  - pyyaml
```
