### ISSUE TITLE
mambaforge link is returning a 404

### ISSUE THREAD

**Issue by lminer** [conda-incubator/setup-miniconda#156]
I'm getting this error when I try an action with mamba forge:

```
  Will fetch Miniforge3 Mambaforge from https://github.com/conda-forge/miniforge/releases/download/Mambaforge/Miniforge3-Mambaforge-Linux-x86_64.sh
  Ensuring Installer...
  Checking for cached Miniforge3@Mambaforge...
  Did not find Miniforge3-Mambaforge-Linux-x86_64.sh Mambaforge in cache
```

Looks like the link is actually: https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh

**Comment by bollwyvl** [comment]
What are the `with` inputs to your action?

**Comment by lminer** [comment]
Here they are:

```yaml
- name: Setup Miniconda
  uses: conda-incubator/setup-miniconda@master
  with:
    activate-environment: separate
    environment-file: environment.yml
    auto-update-conda: false
    auto-activate-base: false
    python-version: 3.7
    use-only-tar-bz2: true
    miniforge-version: Mambaforge
    use-mamba: true
```
