### ISSUE TITLE
wrong pip/python after setup conda

### ISSUE THREAD

**Issue by Borda** [conda-incubator/setup-miniconda#157]
Hello,
I have most of our package requirements in pip file, so I wanted to activate conda and later install the remaining dependencies with pip, but it seems that the GH action still uses the default pip
```yaml
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        channels: conda-forge
        channel-priority: true
        auto-activate-base: true
        use-only-tar-bz2: true

    - name: Update Environment
      run: |
        conda info
        conda install pip
        conda list
        pip --version
```
which correctly install python3.8. in COnda but the last pip version call returns
```
pip 21.0.1 from /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/pip (python 3.6)
```
what am I missing in the confirmation?
btw, this the full build - https://github.com/PyTorchLightning/metrics/pull/127/checks?check_run_id=2188645498
