### ISSUE TITLE
Refactor clean-patched-environment-file to post step

### ISSUE THREAD

**Issue by bollwyvl** [conda-incubator/setup-miniconda#165]
The `clean-patched-environment-file` introduced in #163 created a new chunk of `setup.ts` that is kinda icky, as presently (and probably only) the `yaml` env provider will be doing any patching, and therefore needing cleaning.

However, it is conceivable that other env providers (or other setup steps) might create files that should be cleaned up before giving up the scope of the action.

As soon as we see a second "do this after everything else is done," we should refactor this into a more well-thought-out structure.

**Comment by iameskild** [comment]
@bollwyvl @goanpeca I'm not sure this is the right place for this but a recent PR failed at the `check-manifest` step of the CI build. The reason stated is:
```
missing from VCS:
   setup-miniconda-patched-environment.yml
```
I was able to get around this issue by excluding this file from the MANIFEST.in but I suspect this isn't best-practice. I guess this comment is just for your awareness and to ask if there are other recommended solutions. 
Thanks again for all your work!

**Comment by bollwyvl** [comment]
Sorry for the inconvenience, it's hard to keep everybody happy: previously we created the patched file in `/tmp`, but that broke the `pip: ['-r requirements.txt']` technique, so we started making the file in-place. The intent was to have it clean up the file at the end of the action, but things can always go wrong.

What are the actual values you invoke the action with? What is building?

I'm dealing with satellite internet at present, and nominally vacationing, so it's unlikely a fix is forthcoming for the next couple days from my end.

In light of the above, the quickest work-arounds are probably:
- don't use `python-version` (it's the only thing that will trigger the environment patching)
- move your `environment.yml` someplace that's already excluded from whatever build system you're dealing with so that the neighbor file won't bother you

**Comment by iameskild** [comment]
@bollwyvl apologies for the delayed response. Thank for the update. 
We are currently running our CI through Github Actions, using the values for the "Install Conda" step:
```
- name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: qreport
           auto-update-conda: true
           auto-activate-base: true
           python-version: ${{ matrix.PYTHON_VERSION }} 
           environment-file: environment.yml
```
This isn't urgent so enjoy your vacation!

PS I think we might have met in person in an AI/ML meetup in Atlanta in early 2020, I'm a friend of T.Fast. Hope you're well!
