### ISSUE TITLE
Still having errors with 32-bit miniconda setups

### ISSUE THREAD

**Issue by ktbarrett** [conda-incubator/setup-miniconda#166]
From [here](https://github.com/ktbarrett/find_libpython/pull/13/checks?check_run_id=2221834708#step:3:10). I am specifying `miniconda-version` and still get errors. The following line is to blame (I think, I don't know JS), it seems that it should check if miniconda-version is **not** set and architecture != x64, based on the error message.
https://github.com/conda-incubator/setup-miniconda/blob/35d1405e78aa3f784fe3ce9a2eb378d5eeb62169/src/input.ts#L61-L63

**Comment by chrisjbillington** [comment]
Me too, though I am specifying miniconda-version as "latest". Is the intention that one needs to be specific and not just specify "latest"?

```yaml
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
          miniconda-version: "latest"
```


```
Run conda-incubator/setup-miniconda@v2
  with:
    auto-update-conda: true
    python-version: 3.7
    architecture: x86
    miniconda-version: latest
    activate-environment: test
    auto-activate-base: true
    remove-profiles: true
    clean-patched-environment-file: true
  env:
    PACKAGE_NAME: desktop-app
    SCM_LOCAL_SCHEME: no-local-version
    ANACONDA_USER: labscript-suite
    PURE: false
    NOARCH: false
    pythonLocation: C:\hostedtoolcache\windows\Python\3.7.9\x86
    CONDA_BUILD_ARGS: 
Gathering Inputs...
  Error: 'architecture: x86' requires "miniconda-version"
Error: 1 errors found in action inputs
```
