### ISSUE TITLE
Parsing environment: null byte is not allowed in input

### ISSUE THREAD

**Issue by noeRls** [conda-incubator/setup-miniconda#177]
Hi,

I am running into this error: `Error: null byte is not allowed in input at line 1, column 4` at the setup step `Parsing environment...` of this action.

Here are the github action logs:
```
Run conda-incubator/setup-miniconda@v2
Gathering Inputs...
Creating bootstrap condarc file in /home/runner/.condarc...
Ensuring installer...
Setup environment variables...
Parsing environment...
Error: null byte is not allowed in input at line 1, column 4:
```

Here is my workflow file:
```yaml
name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
    - run: |
        conda info
        conda list
    - run: ./test.sh
```

Here is my `environment.yml` at the root of my repository:
```yaml
name: anaconda-client-env
channels:
  - defaults
dependencies:
  - numpy
  - python=3.8
  - tensorflow-gpu
```

It's worth to mention that I am developing on windows.

What should I do to fix this error?
