### ISSUE TITLE
Environment not being properly activated

### ISSUE THREAD

**Issue by hameerabbasi** [conda-incubator/setup-miniconda#179]
See the run [here](https://github.com/pydata/sparse/runs/2814162414). It cannot find `pip` from conda on the macOS runner and uses the system one, even though it is explicitly listed in the deps in `environment.yml`.

The config for this action is as follows:

```yaml
- uses: conda-incubator/setup-miniconda@v2
  with:
    activate-environment: sparse-dev
    allow-softlinks: true
    environment-file: ci/environment.yml
    python-version: ${{ matrix.python }}
    miniforge-variant: Mambaforge
    use-mamba: true
```
