### ISSUE TITLE
GitHub Action stuck @ creating conda environment

### ISSUE THREAD

**Issue by AngryMaciek** [conda-incubator/setup-miniconda#196]
Great Action! We use it in our research 😊💻
However, there is an issue:
Inside our CI workflow [here](https://github.com/zavolanlab/zarp) we have:

```
      - name: Setup miniconda & zarp root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7.4
          miniconda-version: 4.7.12
          auto-update-conda: false
          environment-file: install/environment.root.yml
          activate-environment: zarp
          auto-activate-base: false
```

This step often gets stuck (seemingly forever) and the whole workflow needs to be restarted. Then it passes. Strange...

**Comment by goanpeca** [comment]
Hi @AngryMaciek, thanks for the kind words and super happy it is useful for your use case.

Now could you point to a CI run that exhibits the issue, so we can take a look?

Also, any particular reason to use

```
          python-version: 3.7.4
          miniconda-version: 4.7.12
```

Those specific versions?

Cheers!

**Comment by AngryMaciek** [comment]
One of the workflow runs which had this problem was here:
https://github.com/zavolanlab/zarp/pull/11/checks?check_run_id=3667711989
But I restarted it, so now it passed.

No, I don't think there was any reason to use these versions... 
I think that we usually develop/test on these so in order to be consistent I set it up in the CI to match our locals.

**Comment by goanpeca** [comment]
>But I restarted it, so now it passed.

If you could start a. "test" PR and see it happen, it would make it easier to take a look :)

**Comment by AngryMaciek** [comment]
I have forked the repo, created a test branch and started the CI. It is stale, please take a look here:
https://github.com/AngryMaciek/zarp-1/runs/3668356973?check_suite_focus=true

**Comment by goanpeca** [comment]
Thanks @AngryMaciek I will wait for it to get killed by Github after running for more than X hours, to see what the logs show :)

**Comment by jaimergp** [comment]
I have never seen this, sadly. It's not even a connection error, just the unpacking getting stuck for some weird reason :/

**Comment by goanpeca** [comment]
Indeed, not sure what might be the issue. Using the installed miniconda (not providing `miniconda-version: 4.7.12`) and updating conda to the desired version might be a workaround @AngryMaciek 

<img width="884" alt="Screen Shot 2021-09-22 at 9 46 27 AM" src="https://user-images.githubusercontent.com/3627835/134366080-9fea895f-ed0a-43df-a770-408c41ffb707.png">

**Comment by keller-mark** [comment]
I seem to be experiencing this same issue. Taking almost an hour to setup miniconda. Any updates? 


```yml
jobs:
  test_demos:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vitessce-python-demos
          environment-file: demos/environment.yml
          python-version: 3.8
          use-mamba: true
          mamba-version: "*"
          auto-activate-base: false
      - run: |
          conda info
          conda list
```

https://github.com/vitessce/vitessce-python/actions/runs/3877173454/jobs/6611874014

<img width="1354" alt="Screen Shot 2023-01-09 at 3 34 39 PM" src="https://user-images.githubusercontent.com/7525285/211403016-667bd2ee-019c-4944-960c-680a75341b20.png">
