### ISSUE TITLE
Error: No installed conda 'base' enviroment found at 

### ISSUE THREAD

**Issue by evencheng-invitae** [conda-incubator/setup-miniconda#203]
GHA:
```
  run-linters:
    name: Run Linters and Annotate
    runs-on: "ubuntu-latest"
    container: ubuntu:latest
    steps:
      - name: Cleanup workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0
      - uses: actions/checkout@v1
        name: Checkout PR
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          auto-update-conda: true
          python-version: "3.7"
          activate-environment: true
```

Output:
```
Run conda-incubator/setup-miniconda@v2
  with:
    auto-activate-base: true
    auto-update-conda: true
    python-version: 3.7
    activate-environment: true
    remove-profiles: true
    architecture: x64
    clean-patched-environment-file: true
/usr/bin/docker exec  d6e54a18e7d3e451feaf1484cee30709ddd0a0a295d7ba00b380f69d0294c607 sh -c "cat /etc/*release | grep ^ID"
Gathering Inputs...
Creating bootstrap condarc file in /github/home/.condarc...
Ensuring installer...
  Can we use bundled Miniconda?
  ... will use bundled Miniconda.
Error: No installed conda 'base' enviroment found at 
```

Do I miss anything so conda is not installed?
