### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by javierggt** [conda-incubator/setup-miniconda#206]
This is more a question than an issue, because I have no idea how this could happen, and I believe it happens in relation to conda. Please forgive me if it is something trivial. I guess it could also be a bash/windows issue. It beats me.

I have the following workflow that I trigger with a repository dispatch. It is a minimal example that runs on windows (I have no issue in Linux and OS X). You can see the runs in my repo [here](https://github.com/javierggt/test-actions):
```
---
name: Test Setup
on:
  repository_dispatch:
    types: [test-setup]

jobs:
  build-conda:
    runs-on: windows-latest
    name: Test
    steps:
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "py38_4.8.3"
          python-version: "3.8"
      - name: Conda build
        if: ${{ github.event.client_payload.build }}
        shell: bash -l {0}
        run: |
          conda install conda-build gitpython git
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: conda-incubator/setup-miniconda
          ref: master
          path: setup
      - name: Change directory
        shell: bash -l {0}
        run: |
          pwd
          ls
          cd setup
          pwd
          ls
```

The `Conda build` step is run only if it is requested in the payload. After that, I check a repository out (I checkout this one). Then I change into the repository local directory and list its contents.

**The strange thing is**: if I skip the `Conda build` step ([run #3](https://github.com/javierggt/test-actions/actions/runs/1587827702)), everything is fine, and the output of the last step is:
```
/d/a/test-actions/test-actions
setup
/d/a/test-actions/test-actions/setup
action.yml
CHANGELOG.md
CONTRIBUTING.md
dist
etc
LICENSE.txt
package.json
package-lock.json
README.md
RELEASE.md
src
tsconfig.json
```
whereas if I do not skip it ([run #4](https://github.com/javierggt/test-actions/actions/runs/1587827882)) the directories are empty and the output is:
```
/d/a/test-actions/test-actions
/d/a/test-actions/test-actions/setup
```

If instead of `conda build`, I do something like `conda list` in the same step, then everything works fine. How can running conda affect checking out a repository **in the following step**, or the working path?

Any idea that can help?
