### ISSUE TITLE
Getting error on miniconda conda-incubator/setup-miniconda@v2.1.1 with no base environment activated

### ISSUE THREAD

**Issue by ajcost** [conda-incubator/setup-miniconda#218]
Using the below yaml:

```yaml
name: QA - Precommit Checks
on: [push]
jobs:
  Precommit-Checks:
    runs-on: self-hosted
    steps:
      - run: echo "Checking branch precommit hooks ..."
      - run: echo "Now running on a ${{ runner.os }} server ..."
      - run: echo "The name of your branch is ${{ github.ref }} ..."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: sigma-sealevel
          environment-file: environment.yml
          python-version: 3.10
          auto-activate-base: false
      - run: |
          pre-commit run --all-files
```

I get a very strange error at Setup Miniconda with

```
Run conda-incubator/setup-miniconda@v2.1.1
Gathering Inputs...
Creating bootstrap condarc file in /home/ubuntu/.condarc...
Ensuring installer...
Error: No installed conda 'base' enviroment found at 
```

Even with the enviroment typo, not sure what that is about

**Comment by czyzi0** [comment]
Hi, I've encountered identical error but when I've specified particular url of installer to use with `installer-url` parameter it seemed to work ok. I don't know why default setting does not work but this may be a temporary workaround.

**Comment by mist2410** [comment]
I have encountered the same issue on a self-hosted Github runner (Ubuntu Azure VM).
In my case, I made sure to install Miniconda on the VM and have the env variable `CONDA` and `PATH` properly set by adding the script `/etc/profile.d/set_conda_envs.sh` with the following content:
```
export CONDA="/home/adminuser/miniconda3"
export PATH="$CONDA/condabin:$PATH"
```

If I execute a step where I run the commands:
```
- name: Check Conda local install
        run: |
          echo $PATH
          echo $CONDA
          conda -h
          conda env list
```
everything works as expected, but when I use `conda-incubator/setup-miniconda@v2.1.1` I get the error:
```
Run conda-incubator/setup-miniconda@v2.1.1
Gathering Inputs...
Creating bootstrap condarc file in /home/adminuser/.condarc...
Ensuring installer...
Error: No installed conda 'base' enviroment found at 
```

@czyzi0 : how does your `conda-incubator/setup-miniconda@v2.1.1` look like? What did you put in the `installer-url` parameter?

**Comment by czyzi0** [comment]
My step with `setup-miniconda` is:
```
- name: Set up env
- uses: conda-incubator/setup-miniconda@v2
- with:
    installer-url: https://repo.anaconda.com/miniconda/Miniconda3-py38_4.11.0-Linux-x86_64.sh
    activate-environment: envname
    enivornment-file: environment.yml
    auto-activate-base: false
```
And it works fine like that.

Hope this helps.

**Comment by goanpeca** [comment]
@mist2410 could you have a default conda installation in your runner so that can be used?

**Comment by mist2410** [comment]
@goanpeca , I tried to install miniconda on my runner, but `conda-incubator/setup-miniconda` fails to find it, even if I try to properly set the env variables `CONDA` and `PATH` (I tested it by printing them out in my Github workflow).
I get the same error mentioned by @ajcost and me in our reports (https://github.com/conda-incubator/setup-miniconda/issues/218#issuecomment-1128675476).

**Comment by micstadsb** [comment]
@goanpeca , yes, I tried (see https://github.com/conda-incubator/setup-miniconda/issues/218#issuecomment-1128859867) but a slightly different custom installer than the one reported in the documentation.
I followed the suggested version from @czyzi0 (see https://github.com/conda-incubator/setup-miniconda/issues/218#issuecomment-1128728941).

Should I try something different? Do you have other suggestions?

**Comment by goanpeca** [comment]
Than ks @micstadsb I guess the solution would be to remove the lines between `# >>> conda initialize >>>` when the process finished... or when it starts (or both)

**Comment by casperdcl** [comment]
The [URL version](https://github.com/conda-incubator/setup-miniconda/issues/218#issuecomment-1128728941) fails when you restart a job (it tries to re-download miniconda and somehow gets confused).

This worked for me:

```yaml
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: ...
        activate-environment: ...
        python-version: ...
        miniconda-version: latest
        auto-activate-base: false
    - shell: bash --login {0}
      run: ...
```
