### ISSUE TITLE
What operating systems support x86 using actions?

### ISSUE THREAD

**Issue by achapkowski** [conda-incubator/setup-miniconda#225]
I am doing the following:

```
name: Python Package using Conda for x86 (32-bit)

on: [workflow_dispatch]

jobs:
  build-x86:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
         python-version: ['3.9']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        architecture: x86
    - name: Install dependencies using Miniconda
      run: |
        conda install conda-build python=${{ matrix.python-version }}
        conda install pyyaml
```

What I am trying to do is use the miniconda installer to get the 32-bit installers so I can build an x86 package.  I can't get the system to build any version of python or OS.   

This is the error I get:

```
Ensuring installer...
  Can we use bundled Miniconda?
  Can we download a custom installer by URL?
  Can we download Miniconda?
  Can we download Miniforge?
Error: No installer could be found for the given inputs
```

Any ideas?
