### ISSUE TITLE
How to activate conda environment for other steps?

### ISSUE THREAD

**Issue by roipoussiere** [conda-incubator/setup-miniconda#226]
I'm trying to use setup-miniconda and I'm stuck on a simple step: 

```yml
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: my-venv
      - name: Info
        run: |
          which python
```

On the next steps I want to use python interpreter of the Conda environment by default. When I do `which python`, I'm expecting to get something like `.../conda/env/my-venv/bin/python` but it's still `/usr/bin/python`.
