### ISSUE TITLE
Can't use the action on `macos-12` executor

### ISSUE THREAD

**Issue by ljmf00** [conda-incubator/setup-miniconda#229]
The new `macos-12` executor is available as public beta for Github Actions. I'm experiencing issues setting up miniconda with this action.

Even though I didn't test it in an isolated environment, I believe this can be reproduced with the following workflow:

```yaml
jobs:
  conda:
    runs-on: macos-12
    steps:
      - name: "Setup miniconda"
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.7'
          auto-activate-base: true
          allow-softlinks: true
```

Log:
```
Run conda-incubator/setup-miniconda@v2
  with:
    auto-update-conda: true
    python-version: 3.7
    auto-activate-base: true
    allow-softlinks: true
    activate-environment: test
    remove-profiles: true
    architecture: x64
    clean-patched-environment-file: true
  env:
    PYTEST_ADDOPTS: --showlocals -vv --durations=10
    PY_COLORS: 1
    TOX_PARALLEL_NO_SPINNER: 1
    DOTNET_ROOT: /Users/runner/.dotnet
Gathering Inputs...
Creating bootstrap condarc file in /Users/runner/.condarc...
Ensuring installer...
  Can we use bundled Miniconda?
  ... will use bundled Miniconda.
Error: No installed conda 'base' enviroment found at
```
