### ISSUE TITLE
Question on function of python-version patch

### ISSUE THREAD

**Issue by jacquelinegarrahan** [conda-incubator/setup-miniconda#244]
The python-version patching is not clear when used with an existing environment.yml file. 

I have an environment.yml file that looks like:
```yaml
name: my-model-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - pydantic
  - lume-model=1.4 
```

From existing documentation, it seems that the python provided should be patched with the python version provided in:
```yaml
  - uses: conda-incubator/setup-miniconda@main
    with:
      mamba-version: "*"
      channels: conda-forge
      activate-environment: my-model-dev
      environment-file: environment.yml
      python-version: ${{ matrix.python-version }}
```

From the workflow, I can see that the patch workflow is being kicked off, but the python pin is not updated and I am unable to resolve my environment using the passed version. Is the environment file being updated only in the case of missing python? Are there ways to override pinned python?

**Comment by anstadnik** [comment]
I'm also interested in this

**Comment by jaimergp** [comment]
It should work if the environment contains a bare `python` requirement (no version), like:

```yaml
name: my-model-dev
channels:
  - conda-forge
dependencies:
  - python  # changed
  - click
  - pydantic
  - lume-model=1.4 
```
