### ISSUE TITLE
CondaValueError: prefix already exists: C:\Miniconda

### ISSUE THREAD

**Issue by yehoshuadimarsky** [conda-incubator/setup-miniconda#25]
Getting this weird error, any ideas?

### Error:
![image](https://user-images.githubusercontent.com/24758845/79678421-720bb180-81c9-11ea-8c3d-c246cf0922a0.png)

```
C:\windows\system32\cmd.exe /D /S /C "C:\Miniconda\condabin\conda.bat env create -f env.yml --quiet"
##[warning]
CondaValueError: prefix already exists: C:\Miniconda



CondaValueError: prefix already exists: C:\Miniconda

##[error]The process 'C:\Miniconda\condabin\conda.bat' failed with exit code 1
```

### workflow file:
```yaml
name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CONDA_ENV_NAME: my-test-env
    runs-on: [windows-latest]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
       auto-update-conda: true
       activate-environment: ${{ env.CONDA_ENV_NAME }}
       environment-file: env.yml
       python-version: ${{ matrix.python-version }}
       auto-activate-base: false
    - name: Show Conda env stuff
      shell: powershell
      run: |
        conda info -a
        conda list
        conda list -n $ENV:CONDA_ENV_NAME
```

### Conda `env.yml` file:
```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  # dev tools
  - black=19.10b0
  - flake8=3.7.9
  - hypothesis=4.54.2
  - ipython=7.11.1
  - matplotlib=3.1
  - mypy=0.761
  - pre_commit=2.*
  - pytest=5.3.4
  - pytest-cov=2.8.1
  - spyder-kernels=0.*

  # core
  - pip=20.*
  - pandas=1.*
  - pyodbc=4.0.28
  - sqlalchemy=1.3.13
  
  # pip dev tools
  - pip:
    - codetiming==1.1
```

**Comment by goanpeca** [comment]
@yehoshuadimarsky you need to define the environment name on the `env.yml` 

### Conda `env.yml` file:
```yaml
name: my-test-env
channels:
  - conda-forge
  - defaults
dependencies:
  # dev tools
  - black=19.10b0
  - flake8=3.7.9
  - hypothesis=4.54.2
  - ipython=7.11.1
  - matplotlib=3.1
  - mypy=0.761
  - pre_commit=2.*
  - pytest=5.3.4
  - pytest-cov=2.8.1
  - spyder-kernels=0.*

  # core
  - pip=20.*
  - pandas=1.*
  - pyodbc=4.0.28
  - sqlalchemy=1.3.13
  
  # pip dev tools
  - pip:
    - codetiming==1.1
```
