### ISSUE TITLE
miniconda install fails on self hosted runner

### ISSUE THREAD

**Issue by GeorgWa** [conda-incubator/setup-miniconda#269]
I have a new windows 10 installation which I would like to use for performance tests with a custom github actions runner.
Unfortunately, the miniconda installation fails as, to my understanding, the installation cannot be found.

I used a very simple action:

```
name: performance testing

on: 
  workflow_dispatch:

env:
  TEST_DATA_DIR: ../_data/

jobs:
  loose_installation:
    name: Performance testing
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Conda info
        run: |
          conda info
```

When run, the conda-incubator/setup-miniconda@v2 fails with the following error:
```
Run conda-incubator/setup-miniconda@v2
Gathering Inputs...
Creating bootstrap condarc file in C:\Windows\ServiceProfiles\NetworkService\.condarc...
Ensuring installer...
Running installer...
  C:\actions-runner\_work\_temp\03d89d[27](https://github.com/org/repo/actions/runs/3761861196/jobs/6394006782#step:3:31)-fe9c-4186-a441-ca7c0ed5858b.exe /InstallationType=JustMe /RegisterPython=0 /S /D=3
...
miniconda is installed succesfully
...
No installed conda 'base' environment found at 3!If you are using this action in a self-hosted runner that already provides its own Miniconda installation, please specify its location with a `CONDA` environment variable. If you want us to download and install Miniconda or Miniforge for you, add `miniconda-version: "latest"` or `miniforge-version: "latest"`, respectively, to the parameters for this action.
```
For some reason the instalation path is set to `/D=3` although `C:\Windows\ServiceProfiles\NetworkService\miniconda3` is used during miniconda installation. Please let me know if you need more information or logs.
