### ISSUE TITLE
Sporadic `CondaError: KeyboardInterrupt`

### ISSUE THREAD

**Issue by Molkree** [conda-incubator/setup-miniconda#270]
We have a rather big and complicated [workflow](https://github.com/intel/cve-bin-tool/blob/a93f003ad03d05968f6ed428de2b16c4b8c3abfa/.github/workflows/testing.yml) in CI but [the bit](https://github.com/intel/cve-bin-tool/blob/a93f003ad03d05968f6ed428de2b16c4b8c3abfa/.github/workflows/testing.yml#L297-L319) using miniconda looks like this:
```yml
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase to reset cache if requirements.txt file has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: pdftotext
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install pdftotext, reportlab and cve-bin-tool
        run: |
          conda install -c conda-forge python=3.10 poppler pdftotext
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --upgrade reportlab
          python -m pip install --upgrade -r dev-requirements.txt
          python -m pip install --upgrade .
```
I am seeing sporadic `CondaError: KeyboardInterrupt` during the last step (at different stages). [One](https://github.com/Molkree/cve-bin-tool/actions/runs/3809940028/jobs/6481676982#step:14:28), [two](https://github.com/intel/cve-bin-tool/actions/runs/3798269439/jobs/6459855451#step:14:27), [three](https://github.com/intel/cve-bin-tool/actions/runs/3794317228/jobs/6452266387#step:14:332). Obviously there's no user to interrupt miniconda from the keyboard in GitHub VM. I'm unsure if it's a miniconda bug or maybe something to be reported to conda/GitHub.
