### ISSUE TITLE
Sporadic failures using `mamba-version: "*"`

### ISSUE THREAD

**Issue by victorlin** [conda-incubator/setup-miniconda#274]
I'm aware that using `mamba-version` is an experimental feature, and some instability can be expected.

However, I've noticed that it's been failing more often than usual on at least two repos managed by my team @nextstrain.

The [error](https://github.com/nextstrain/augur/actions/runs/3885934348/jobs/6633421678) is not very useful:

```
##[error]The process '/usr/share/miniconda/condabin/conda' failed with exit code 1
```

I've compared a [failing run](https://github.com/nextstrain/augur/actions/runs/3885934348/jobs/6633421678) with a [successful re-run](https://github.com/nextstrain/augur/actions/runs/3885934348/jobs/6634748795) of the same workflow. There are some notable differences in the output of `conda config --show`:

```diff
75d74
< allowlist_channels: []
110c109
< default_python: 3.10
---
> default_python: 3.9
123a123
> experimental_solver: classic
125d124
< fetch_threads: 5
137d135
< number_channel_notices: 5
165d162
< solver: classic
181a179
> whitelist_channels: []
197c195
< no change     /usr/share/miniconda/lib/python3.10/site-packages/xontrib/conda.xsh
---
> no change     /usr/share/miniconda/lib/python3.9/site-packages/xontrib/conda.xsh
```

I've already found a workaround by using `solver=libmamba` instead of `mamba-version` (https://github.com/nextstrain/augur/commit/344ed514dc7e70a6ce70307f470ea2745eb82923). However, I still do not understand why there are differences in Python versions and other conda config between two runs of the same workflow.

_(originally from https://github.com/nextstrain/augur/issues/1125)_

**Comment by joamatab** [comment]
observing the same today

https://github.com/gdsfactory/gdsfactory/actions/runs/3906659862/jobs/6675080754

**Comment by joshuailevy** [comment]
Also observing this. https://github.com/andersen-lab/Freyja/actions/runs/3907050506. Thanks @victorlin for posting the workaround.

**Comment by jongyoul** [comment]
I also found the same error on https://github.com/apache/zeppelin/actions/runs/3901061183/jobs/6665542729

**Comment by traversaro** [comment]
If you are not interested in using `defaults`, a possible strategy is to use `mambaforge` instead of miniconda, see for example:
* https://github.com/robotology/robotology-superbuild/pull/840
* https://github.com/robotology/robometry/pull/141
* https://github.com/robotology-playground/yarp-devices-ros2/pull/44
* https://github.com/gazebosim/gazebo-classic/pull/3287

**Comment by victorlin** [comment]
@traversaro thanks, I've updated the list of workarounds in the issue description and put that one first since it is the more popular one.

**Comment by victorlin** [comment]
> If you are not interested in using `defaults`, a possible strategy is to use `mambaforge` instead of miniconda

Note that `defaults` is included in the generated `.condarc` regardless of `miniforge-variant`, and you'll have to use `nodefaults` or `--override-channels` to truly get away from it. See #207 for more info.

**Comment by kthyng** [comment]
I have been having the following error with `ubuntu-latest`:

```
PackagesNotFoundError: The following packages are missing from the target environment:
    - defaults/linux-64::conda==22.11.1=py310h06a4308_4[md5=07e2e8a698cf1e7f580b9efcae72184e]
```

with this in my `test.yaml` 
```
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*" # activate this to build with mamba.
          channels: conda-forge, defaults # These need to be specified to use mamba
          channel-priority: true
          environment-file: ci/environment-py${{ matrix.python-version }}.yml

          activate-environment: test_env_cmocean
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
```

(example PR with errors earlier: https://github.com/matplotlib/cmocean/pull/88)

and workaround 1 above worked for me!
