### ISSUE TITLE
`Adding tools to 'base' env...` fails to resolve

### ISSUE THREAD

**Issue by jan-janssen** [conda-incubator/setup-miniconda#275]
This behavior started last week. 

Example job that crashed: 
https://github.com/mailsort/pygmailsorter/actions/runs/3942308109/jobs/6745797447

```
Adding tools to 'base' env...
  Do we need to update conda?
  Do we need to update mamba?
  ... we will update mamba.
  Warning: Mamba support is still experimental and can result in differently solved environments!
  ... we will perform post-install steps after we update mamba.
  Do we need to update python?
  Do we need to update conda-build?
  /usr/share/miniconda/condabin/conda install --name base mamba=*
  Collecting package metadata (current_repodata.json): ...working... done
  Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
  Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
  Collecting package metadata (repodata.json): ...working... done
  Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
  Solving environment: ...working... 
  Found conflicts! Looking for incompatible packages.
  This can take several minutes.  Press CTRL-C to abort.
```

The corresponding GitHub action:
https://github.com/mailsort/pygmailsorter/blob/main/.github/workflows/unittest.yml

```
# This workflow is used to run the unittest of pyiron

name: Unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']
        include:
        - operating-system: ubuntu-latest
          python-version: 3.8
        - operating-system: ubuntu-latest
          python-version: 3.9

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        environment-file: .ci_support/environment.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: coverage run --omit pygmailsorter/_version.py -m unittest discover tests
```

Is there any known bug?
