### ISSUE TITLE
Failure with ubuntu-latest but not with macos-latest and windows-latest

### ISSUE THREAD

**Issue by ubaldot** [conda-incubator/setup-miniconda#278]
Here is what I have in my workflow file:

```
     - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: ./environment.yml
```

With ubuntu-latest there are a number of conflicts (excerpt below) that make the action to fail.

```
nsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (readline):

  - mamba -> conda[version='4.6.*,<4.13.0|4.6.*|4.7.*,<4.13.0|>=22.11.0,<23.4|>=4.8,<23.4|>=4.8,<5|>=4.8|>=4.8,<4.13.0|>=4.7.12,<4.13.0|>=4.7.12,<4.8']
  - mamba -> conda[version='>=4.8,<23.4'] -> conda-package-handling[version='>=1.3.0']
  - mamba -> conda[version='>=4.8,<23.4'] -> pluggy[version='>=1.0.0']
  - mamba -> conda[version='>=4.8,<23.4'] -> pycosat[version='>=0.6.3']
  - mamba -> conda[version='>=4.8,<23.4'] -> pyopenssl[version='>=16.2.0']
  - mamba -> conda[version='>=4.8,<23.4'] -> requests[version='>=2.18.4,<3|>=2.20.1,<3']
```

This won't happen with macos-latest and windows-latest.
