### ISSUE TITLE
using conda-lock.yml result in "EnvironmentSectionNotValid". 

### ISSUE THREAD

**Issue by ubaldot** [conda-incubator/setup-miniconda#284]
I created a conda-lock.yml and I followed the guide in the README in this repo. 

```
  mamba_tests:
    name: Tests with conda/mamba
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: ./conda-lock.yml
```

When running the workflow, I get the following error:

```
...
Updating 'explicit-env' env from conda env update...
  /usr/share/miniconda/condabin/conda env update --name explicit-env --file ./conda-lock.yml
  /home/runner/work/_actions/conda-incubator/setup-miniconda/v2/dist/setup/index.js:26904
                              throw new Error(`"${command}" failed with "${forced_error}"`);
                              ^
  
  Error: "/usr/share/miniconda/condabin/conda,env,update,--name,explicit-env,--file,./conda-lock.yml" failed with "EnvironmentSectionNotValid"
```

I generated the conda-lock file with `conda-lock -f pyproject.toml`
