### ISSUE TITLE
`conda-incubator/setup-miniconda@v2` with `miniforge-version: "latest"` installs a fairly old conda and mamba

### ISSUE THREAD

**Issue by valeriupredoi** [conda-incubator/setup-miniconda#288]
Hey guys, first off - many thanks for this action, it's brilliant and we've been using it a for a long time now, in quite a few projects! Bit of a nag though, here (and this doesn't really bite just yet, although I've had some issues with conda lockfile builds due to it): the conda base version is now pretty much stuck at 23.1.0 and mamba at 1.4.1 - which are pretty old, and will need updating; one workaround I found to work is to install mamba >=1.4.8 after, as a separate step, that updates conda to a new version 23.5 and mamba to 1.4.9. Here is the minimal use we have:
```yaml
jobs:
  create-verify-lock-file:
    name: Create and verify conda lock file for latest Python
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: esmvaltool-fromlock
          python-version: "3.11"
          miniforge-version: "latest"
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Update and show conda config
        run: |
          conda update -n base -c conda-forge conda
          conda info
          conda list
          conda config --show-sources
          conda config --show
          # setup-miniconda@v2 installs an old conda and mamba
          # forcing a modern mamba updates both mamba and conda
          conda install -c conda-forge "mamba>=1.4.8"
          conda --version
          mamba --version
...
```

I cah help with this, just let me know! Cheers :beer:
