### ISSUE TITLE
Slow solution times on ubuntu-latest

### ISSUE THREAD

**Issue by WardLT** [conda-incubator/setup-miniconda#297]
My solution times for both `mamba` and `conda` have increased from ~3 minutes to >30 in the past week even though I have not changed the environment file.

Do you know what could be going on? 

- Fast Solution: [logs_973.zip](https://github.com/conda-incubator/setup-miniconda/files/13044258/logs_973.zip)
- Slow Solution: [logs_1054.zip](https://github.com/conda-incubator/setup-miniconda/files/13044305/logs_1054.zip)

**Comment by jaimergp** [comment]
It looks like it's not timing out in your environment solving, but before that, when it's trying to install `mamba` on the bundled Miniconda. I'd give Miniforge a try using this config:

```yaml
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: envs/environment-cpu.yml
          activate-environment: test
          auto-activate-base: true
          auto-update-conda: false
          remove-profiles: true
          architecture: x64
          clean-patched-environment-file: true
          run-post: true
          use-mamba: true
          miniforge-version: latest
```

It includes `mamba` already, so there's no need to install it.
