### ISSUE TITLE
ImportError: No module named conda.cli

### ISSUE THREAD

**Issue by VascoSch92** [conda-incubator/setup-miniconda#298]
Hey, 
i have a really strange problem. 

I have two projects where i use the same identical workflow:

```yaml
...
  steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
...
```

The problem is that in one project, it works fine, while in the other i have the following error:
```
 Traceback (most recent call last):
    File ".../condabin/conda", line 12, in <module>
      from conda.cli import main
  Warning: ImportError: No module named conda.cli
```

Do you have an idea what can be? I'm using self-hosted runner. 

Thanks :-)

**Comment by mattwthompson** [comment]
Do you have full workflows somebody could use to reproduce this behavior? Logs?

**Comment by VascoSch92** [comment]
This is the complete workflow

```yaml
name: Linting with Ruff

on:
  pull_request:
    branches:
      - '**'  # the workflow is activated on every PR
      
jobs:
  linting_with_ruff:
    name: Linting with Ruff
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: ruff
      - name: Install Ruff
        shell: bash -el {0}
        run: |
          conda activate ruff
          conda install -c conda-forge ruff
      - name: Linting with Ruff
        shell: bash -el {0}
        run: |
          ruff check . --config=ruff.toml
```

1.  The workflow crashes at the step `uses: conda-incubator/setup-miniconda@v2`
2. I have another repository with the same (copy/paste) workflow and in the other repository works
3. can it be that it is because of some env variables? Like PATH. I don't know how `conda-incubator/setup-miniconda@v2` works under the hood

thank you for your help
