### ISSUE TITLE
changing the cwd

### ISSUE THREAD

**Issue by nick-youngblut** [conda-incubator/setup-miniconda#31]
I'm trying to use `setup-miniconda` with my python package setup. The default github workflow for python package ci was working:

```
name: traitar3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -s --script-launch-mode=subprocess
```

...and here's my yaml when incorporating `setup-miniconda`:

```
name: traitar3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: traitar3
    - name: conda env create
      shell: bash -l {0}
      run: |
        conda info -a
        conda install python=${{ matrix.python-version }} bioconda::hmmer scipy pandas numpy matplotlib
    - name: package install
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-dependency pytest-console-scripts
        python setup.py install
    - name: Test with pytest
      run: |
        pytest -s --script-launch-mode=subprocess
```

The `setup-miniconda` version always throws the error: `python: can't open file 'setup.py': [Errno 2] No such file or directory`. I'm guessing that either `uses: goanpeca/setup-miniconda@v1` or `shell: bash -l {0}` is changing the working directory, so then `setup.py` cannot be found. I've been trying to debug this for a while with a number of approaches and haven't found a solution. Any help would be appreciated. 

It would be helpful to include python package setup in one of the `setup-miniconda` examples.

**Comment by goanpeca** [comment]
Hi, thanks for the report. You need to use shell: bash -l {}. On all steps.

The Readme examples show this as well as the IMPORTANT notice.

**Comment by goanpeca** [comment]
It should look like:

```yaml
name: traitar3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: traitar3
    - name: conda env create
      shell: bash -l {0}
      run: |
        conda info -a
        conda install python=${{ matrix.python-version }} bioconda::hmmer scipy pandas numpy matplotlib
    - name: package install
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-dependency pytest-console-scripts
        python setup.py install
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest -s --script-launch-mode=subprocess
```

**Comment by nick-youngblut** [comment]
Sorry, I should have mentioned that I had already tried adding `bash -l {0}` for all steps. I still get the `python: can't open file 'setup.py': [Errno 2] No such file or directory` error regardless of whether I use `bash -l {0}` for all steps or not.

**Comment by goanpeca** [comment]
You need to add a checkout action otherwise the code is not there.

**Comment by goanpeca** [comment]
See: https://github.com/actions/checkout

**Comment by nick-youngblut** [comment]
Yep, that's what I was missing. Thanks for the help. I'm guessing that there's multiple ways of integrating multiple checkouts, but this at least worked for me:

```
name: traitar3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: traitar3
    - name: conda env create
      shell: bash -l {0}
      run: |
        pwd
        conda info -a
        conda install python=${{ matrix.python-version }} bioconda::hmmer scipy pandas numpy matplotlib
    - uses: actions/checkout@v2
    - name: package install
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-dependency pytest-console-scripts
        python setup.py install
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest -s --script-launch-mode=subprocess
```
