### ISSUE TITLE
Environment not activated with miniforge on windows

### ISSUE THREAD

**Issue by k-dominik** [conda-incubator/setup-miniconda#324]
Hello there,

first of all thank you for developing/maintaining such a useful package.

I recently started using miniforge locally for everything, and thought I want to mirror this on CI, too.
On windows it doesn't seem to activate the environment (here `test-env `) though.

This version does not work:

```yaml
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          miniforge-version: latest
          auto-update-conda: true
          conda-solver: libmamba
      - name: windows test
        shell: cmd /C CALL {0}
        run: >-
          conda info && conda list  && SET
```

whereas the one not using miniforge works:

```yaml
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          auto-update-conda: true
          conda-solver: libmamba
      - name: windows test
        shell: cmd /C CALL {0}
        run: >-
          conda info && conda list  && SET
```

Would be cool if this could get fixed. Not a typescript person, otherwise I'd chomp through the code myself. Of course if you have any pointers where to look at specifically, will be happy to do so.

Cheers
Dominik
