### ISSUE TITLE
Python version not from activate conda environment?

### ISSUE THREAD

**Issue by mattrobin** [conda-incubator/setup-miniconda#329]
Hello! I'm using this action to create and activate a conda environment, but it doesn't seem the version of Python and Pip are those in the conda environment. I'm using the shell specification as directed in the notes, and conda seems to be available and active in the step. But the Python and Pip versions still point to the system defaults. Is this the expected case? If so, what's the appropriate way to make sure the pathing is set for the conda environment for the step, as the rest of my build expects the conda environment versions to be the ones to default to. Below I have a minimal version of the GitHub Actions script that uses this action, then shows the path to the default Python and Pip. I have also attached a link to this workflow being run. Thank you for your time!

```yaml
name: use_conda

on: [push, pull_request]

jobs:
  use_conda:
    name: ${{ matrix.os }}_${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version: ['3.9']

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: conda_env
          use-only-tar-bz2: true
          python-version: ${{ matrix.python-version }}

      - name: check_info
        shell: bash -el {0}
        run: |
          conda info
          conda list
          which pip
          which python
```

https://github.com/mattrobin/conda_github_actions_check/actions/runs/7433273757/job/20226079152
