### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by goanpeca** [conda-incubator/setup-miniconda#34]
Explore something like

```
- uses: actions/cache@v1
  with:
    path: ~/conda_pkgs
    key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
    restore-keys: |
      ${{ runner.os }}-conda-
- run: conda config --add ~/conda_pkgs
```
