### ISSUE TITLE
Bit hard to figure out what to type for a local file on windows in Installer-Url

### ISSUE THREAD

**Issue by moorepants** [conda-incubator/setup-miniconda#341]
I spent quite some time this morning figuring this out as it wasn't obvious from the docs or examples. It may be obvious for a Javascript developer that knows how this works:

```javascript
// Node program to demonstrate the  
// URL.fileURLToPath() API as Setter 
  
// Importing the module 'url'  
const url = require('url'); 
  
// Some random path from system 
const file = 'file:///C:/path/example/gfg'
   
// Converting the file to properly encoded path 
console.log(url.fileURLToPath(file)) 
```

which returns:

```
 C:\path\example\gfg
```

taken from: https://www.geeksforgeeks.org/node-js-url-fileurltopath-api/

I finally got a local exe to build on a Github action with:

```yaml
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          installer-url: file:///D:/r/repoowner/reponame/anaconda-installer-Windows-x86_64.exe
```

I can also probably remove the full path, but the keys things are 1) use forward slashes, even if you are on windows and 2) use three forward slashes after `file:`.

It could be helpful to give an example of this in the docs of this repo. Thanks for the action!
