### ISSUE TITLE
Github-hosted runners for OSX no longer carry a bundled conda installatino

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/setup-miniconda#344]
See https://github.com/conda/conda-standalone/actions/runs/8796238715/job/24143815312?pr=67.

`macos-latest` runners now default to macOS 14 on ARM64. This breaks the assumption of `macos-latest == x86_64`. Just a heads up!

We should document this.

**Comment by jaimergp** [comment]
We should maybe install latest Miniconda if `$CONDA` is not found in a Github-hosted runner to maintain previous behavior. Self-hosted behavior should not be modified, though.

**Comment by jaimergp** [comment]
Yes, I'm observing it some repos already. See the linked CI run above.

**Comment by mattwthompson** [comment]
Must have happened overnight? Wonder if there'll be an announcement today then

**Comment by mattwthompson** [comment]
I'm not seeing this change live: https://github.com/mattwthompson/gha-sandbox/actions/runs/8803326872/job/24161162575#step:3:5

**Comment by jaimergp** [comment]
Yep, you got macos-12 there (check first step). This will take 12 weeks, and we are currently starting the 4th-ish. It might hit you latee, but it will 😁

**Comment by briantoby** [comment]
Looking forward, is it likely there will be a time when only MacOS/ARM-based runners are available? If so, should there be a way to specify that one wants to use a x86_64 miniconda even if running on ARM? I can imagine that I will want to build for x86_64 for several more years. It seems to me that tying the CPU architecture to a specific runner is going to be a problem down the road.

**Comment by jaimergp** [comment]
There's an `architecture` setting, and also `installer-url` if everything fails, so I think it should be fine.

**Comment by valeriupredoi** [comment]
Hi @jaimergp - good catch! And we've literally just noticed this by upgrading to v4, see https://github.com/ESMValGroup/ESMValCore/pull/2411#issuecomment-2102550298 - the problem is that in the future there will be fewer and fewer nodes that will run v3 (GHA already toss warnings that one should update the action to latest version, since such and such node are the only ones able to execute the older version). BTW using `macos-latest` and `setup-miniconda@v3` works in the sense that the Setup job installs the arm64 container but the deps are the generic `osx-64` builds (see my comment with links to GHA runs, in our PR). Cheers muchly for the good work you folks do here BTW :beer:

**Comment by valeriupredoi** [comment]
I found out that forcing the Intel architecture as:
```yaml
  osx:
    runs-on: "macos-latest"
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        architecture: ["x64"]
      fail-fast: false
    name: OSX Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          architecture: ${{ matrix.architecture }}
          activate-environment: esmvalcore
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-version: "latest"
          miniforge-variant: Mambaforge
          use-mamba: true
 ```
 
 [works biutifully](https://github.com/ESMValGroup/ESMValCore/actions/runs/9017745776/job/24776827979?pr=2411) even with the ARM64 processor and v4, well at least for now, before they diverge completely :partying_face:
