### ISSUE TITLE
Cannot create simple environment with custom environment.yml file

### ISSUE THREAD

**Issue by nik123** [conda-incubator/setup-miniconda#363]
I'm trying to create conda environment using custom environment file with setup-miniconda action and I fail.

My github aciton file looks the following:

```
name: my-conda-env

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: my-conda-env
        environment-file: conda-env.yml
        python-version: 3.10
        auto-activate-base: false
```

I've created the following environment file:

```
name: my-conda-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
    - numpy==1.26.3
    - pandas==2.1.4
```

However, when I run Github workflow I get the following error:

```
  PackagesNotFoundError: The following packages are not available from current channels:
  
    - python[version='3.1.*,3.10.*']
```
