### ISSUE TITLE
Mamba example 6 seems to be failing

### ISSUE THREAD

**Issue by dsobral** [conda-incubator/setup-miniconda#366]
https://github.com/conda-incubator/setup-miniconda/actions/workflows/example-6.yml

**Comment by oursland** [comment]
The issue is that `defaults/noarch::conda-libmamba-solver-23.12.0` is being installed, even if you remove the `defaults` channel.  This is not compatible, nor should it be selected.

**Comment by isaacsanders** [comment]
This also seems like it could be a problem with the release of mamba 2 last week.

**Comment by isaacsanders** [comment]
A person on a team I work with used a non-2.0.0 `mamba-version` parameter, and it worked.

**Comment by jaimergp** [comment]
See the implicit channels PR at #467, we need `condabin/mamba` present in mamba v2 too.

**Comment by philmod-h** [comment]
We started to get failures like `ERROR: executing pre_install.sh failed` yesterday. 

Is there any way to fix it short term?

Our step:

```
- uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: ...
          use-mamba: true
          python-version: "3.10.14"
```

**Comment by jaimergp** [comment]
Use Miniforge, which is identical to Mambaforge these days. Mambaforge is getting sunset by EOY.

**Comment by mattwthompson** [comment]
`mamba-version: "1.5.10"` works for me

**Comment by jaimergp** [comment]
A fix for mamba v2 is underway at https://github.com/conda-incubator/setup-miniconda/pull/368, but I'm facing some issues in Windows. If someone wants to give it a try, I guess this would work:

```yaml
      - uses: conda-incubator/setup-miniconda@fix-mamba-v2
        with:
          miniforge-variant: Miniforge
          miniforge-version: latest
          use-mamba: true
          mamba-version: "*"
```
