### ISSUE TITLE
Setting up miniforge and a specific python version

### ISSUE THREAD

**Issue by javierggt** [conda-incubator/setup-miniconda#379]
Hi,

I am trying to setup and environment using miniforge (latest) and a specific python version (3.11). In the following workflow, the python-version argument is ignored, and I get python 3.12. If I remove the `miniforge-version` line, then I get python 3.11, but I would like to use miniforge. 

```
on:
  repository_dispatch:
    types:
      - miniforge-test

jobs:
  build:
    runs-on: ubuntu-latest
    name: Setup Miniforge
    steps:
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        python-version: 3.11
    - name: Env List
      run: |
        conda config --show channels
        conda list
```

I'm not doing anything wrong, am I?

**Comment by javierggt** [comment]
and if I use the following (not using miniforge, but trying to remove the default channels), I can still see the anaconda channels in the last step

```
on:
  repository_dispatch:
    types:
      - miniforge

jobs:
  build:
    runs-on: ubuntu-latest
    name: Miniforge
    steps:
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        conda-remove-defaults: "true"
        channels: conda-forge
    - name: Env List
      run: |
        conda config --show channels
        conda list
```

Basically, I want python 3.11, conda-forge, and no anaconda channels, but I don't seem to find the way to do it.

I also want mamba, but I'd take anything that works, and getting the right channels takes priority. Miniforge would be what I want.
