### ISSUE TITLE
Need to support Linux arm64 hosted runners

### ISSUE THREAD

**Issue by wojiushixiaobai** [conda-incubator/setup-miniconda#385]
- https://github.com/orgs/community/discussions/148648

```yaml
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    - uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        channels: conda-forge
        channel-priority: true
        activate-environment: upload
        miniforge-version: latest
```
```log
Ensuring installer...
  Can we use bundled Miniconda?
  Can we download a custom installer by URL?
  Can we download Miniforge?
  ... will download Miniforge.
  Will fetch Miniforge3 latest from https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-arm64.sh
  Ensuring Installer...
  Checking for cached Miniforge3@latest...
  Did not find Miniforge3-Linux-arm64.sh latest in cache
Error: Unexpected HTTP response: [40](https://github.com/loong64/openblas-libs/actions/runs/12850519235/job/35830276751#step:12:43)4
```

`Miniforge3-Linux-arm64.sh` --> `Miniforge3-Linux-aarch64.sh`

- https://github.com/conda-incubator/setup-miniconda/issues/312#issuecomment-1918058490

If anyone is interested in a quick workaround until it is properly supported.
```yaml
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    - uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        architecture: aarch64
        channels: conda-forge
        channel-priority: true
        activate-environment: upload
        miniforge-version: latest
```

**Comment by jaimergp** [comment]
Thanks for the report, I'll take a look shortly.

**Comment by jaimergp** [comment]
@wojiushixiaobai, would you let me know if this works as a fix?

```yaml
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    - uses: conda-incubator/setup-miniconda@linux-aarch64
      with:
        miniforge-version: latest
```
