### ISSUE TITLE
Getting free-threading Python build as default

### ISSUE THREAD

**Issue by briantoby** [conda-incubator/setup-miniconda#395]
I'm using the following in my workflow (slightly cleaned up):

```
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.13"]
    runs-on: 'windows-latest'
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install
        shell: bash -el {0}
        run: |
          conda install python=${{ matrix.python-version }} numpy=2.2 scipy requests pytest git gitpython -c conda-forge --override-channels --quiet
```

And the Python I get is this: 

```
Python 3.13.2 experimental free-threading build | packaged by conda-forge | (main, Feb 17 2025, 13:52:36) [MSC v.1942 64 bit (AMD64)]
```

If I want to get the normal Python interpreter with the GIL, I need to force that by asking for python-gil
```
          conda install python-gil python=${{ matrix.python-version }} numpy=2.2 scipy requests pytest git gitpython -c conda-forge --override-channels --quiet
```

Am I doing something wrong to cause the free-threading version to be selected by default?
