### ISSUE TITLE
mamba on windows "mamba: command not found"

### ISSUE THREAD

**Issue by AndrewAnnex** [conda-incubator/setup-miniconda#59]
on a currently private repo I am trying to use mamba to build on mac/linux/windows but I am running into a command not found error on the windows worker, seems like mamba is not available even after successful install as show in the logs.

partial config:
```
test_runner:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pangeo_test
          auto-update-conda: true
          use-only-tar-bz2: true
      - name: conda info
        shell: bash -l {0}
        run: |
          conda info
      - name: mamba install packages
        shell: bash -l {0}
        run: mamba install ... (command not found error here)
```

**Comment by jaimergp** [comment]
Would it be possible to post a reproducible case for a public repo? I can look into it!

**Comment by AndrewAnnex** [comment]
Hey Jamie, I think that code block above is effectively a reproducible example. It has been a while since I looked at this but in that project I hit the mamba issue before anything relating to my code. I could make a new public repo with that GitHub action configured as well if that will help

-Andrew Annex

**Comment by jaimergp** [comment]
> I could make a new public repo with that GitHub action configured as well if that will help

Yeah, that will help immensely, thanks!

**Comment by AndrewAnnex** [comment]
@jaimergp I made a demo repo and see that the issue is occuring in this runner: https://github.com/AndrewAnnex/test_setup_miniconda_github_action/runs/1140527924

It looks like maybe the "activate-environment" flag is the issue, it is installing mamba to the base environment, but since I don't have an environment yaml file and I specify to create a new environment and activate it, the scripts don't seem to install mamba elsewhere like it does with the ubuntu workers. 

I think making an environment yaml with mamba as a dependency would fix that, but I don't know if mamba would be used to bootstrap that new environment so I think I would loose the benefits of mamba...

**Comment by jaimergp** [comment]
Thanks! I'll add this to my list... it's definitely interesting!

**Comment by jaimergp** [comment]
Behavior should be the same on Ubuntu (we only install `mamba` on `base`), so there's definitely a `%PATH%` issue there... 

`${MINICONDA}/condabin` should always be on PATH, and that's where both `conda` and `mamba` are called from. This is independent of activated environments. On Windows, the absolute path to mamba is `C:\Miniconda\condabin\mamba.bat` and it's being used in the setup steps. You could try using that abs path instead, but let's see if we can have `mamba` working.

`printenv` reveals that PATH does contain it: https://github.com/AndrewAnnex/test_setup_miniconda_github_action/runs/1140527924#step:4:158

The only difference I see is that you are using inline YAML instead of the "paragraph YAML" pipe style. It _shouldn't_ have any difference, but I've seen weirder things happen. Just to make sure, can you do this:

```yaml
      - name: mamba install packages
        shell: bash -l {0}
        run: |
          conda install jupyter
          mamba install jupyterlab
```
