### ISSUE TITLE
Caching troubles & questions

### ISSUE THREAD

**Issue by MGough** [conda-incubator/setup-miniconda#65]
I'm trying to take advantage of caching of dependencies. It seems like whatever I do the`setup-miniconda` action takes just as long regardless of whether I've cached my dependencies or not.

```yaml
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 5
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: myenvname
        channel-priority: strict
        environment-file: environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
```
Have I made a mistake here that is preventing `setup-miniconda` from loading the packages from `~/conda_pkgs_dir` as specified in the docs? 

**Important note** Possibly worth documenting, removing `python-version: 3.7` from the step resulted in a faster build, but still no advantage when caching. I was seeing much slower build times as the step would hang on installing python 3.7.

My environment file looks a bit like this:
```yaml
name: myenvname
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - numpy=1.17.4
  - pandas=0.25.3
  - pytorch=1.4.0
  - pip=20.0.2
  - pip:
    - coverage==5.0.3
```

It seems like some dependencies are downloading regardless of the fact that they were stored in the cache (the caching step is successful and it shows a reasonable size).
```zsh
# Updating conda environment from yaml file...
##############################################

/usr/share/miniconda/condabin/conda env update --file environment.yml --name myenvname
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Ran pip subprocess with arguments:
['/usr/share/miniconda/envs/my-org/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/runner/work/my-org/my-repo/condaenv.p1divyve.requirements.txt']
Pip subprocess output:
Collecting coverage==5.0.3
  Downloading coverage-5.0.3-cp37-cp37m-manylinux1_x86_64.whl (227 kB)
```

It seems like it's not picking up the files that were restored from the cache, what am I missing?
Also should the updated `cache@v2` be supported?

**Comment by MGough** [comment]
Oh, I missed a comment in my earlier search. It wasn't clear to me that the pip packages are separately cached even when using conda. I'll try also caching those

https://github.com/goanpeca/setup-miniconda/issues/54#issuecomment-655187159

**Comment by goanpeca** [comment]
Hi @MGough, thanks for the report:

>It wasn't clear to me that the pip packages are separately cached even when using conda.

Yes, that is correct.

Looking at your env file it seems you are mixing quite a bunch of channels, so:
```
  - pytorch
  - anaconda
  - conda-forge
  - defaults
```

First: `anconda` and `defaults` are the same, except `defaults` is served statically (and faster) whereas `anaconda` is mirrored in to anaconda.org/anaconda, serve dynamically (and hence slower)

I would suggest using just defaults.

Second: Why are you using defaults and conda-forge? Normally you would use one or the other since there are binary incompatibilities on some packages. 

How about something like:

```yaml
name: myenvname
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - numpy=1.17.4
  - pandas=0.25.3
  - pytorch=1.4.0
  - coverage==5.0.3
```

?
