### ISSUE TITLE
Micromamba + cache full example

### ISSUE THREAD

**Issue by adriangb** [conda-incubator/setup-miniconda#66]
Hi, I'm trying to get the absolute fastest times, especially on windows. I see that over at mamba, micromamba is soon going to support windows soon ([link](https://gist.github.com/wolfv/fe1ea521979973ab1d016d95a589dcde)) and support for installing form files at some point (https://github.com/TheSnakePit/mamba/issues/461). It would be really cool to be able to use this action + cache + micromamba for what I assume is going to be blazing fast installs. Once they get windows working (or maybe before) it would be great to get support and a full example of that combination here.

I would imagine this would look something like this:

```yaml
     - name: Cache conda/mamba
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('test-env.yml') }}

      - name: Setup micromamba
        uses: goanpeca/setup-miniconda@v1
        with:
          channels: conda-forge
          activate-environment: test
          micromamba-version: "*"
          use-only-tar-bz2: true  # requried for caching
          environment-file: test-env.yml

      - name: Show conda environment
        shell: bash -l {0}
        run: |
          micromamba list
```

Hopefully this would the first run download and install `micromamba` and then use `micromamba` to install the `test` environment using `test-env.yml`.

Subsequent runs would then use `micromamba` from the cache (i.e. no need to re-download and re-install `micromamba` since it's a single file) and just activate/update the `test` env.

**Comment by goanpeca** [comment]
Hi @adriangb thanks for the suggestion. 

When `micromamba` becomes available, it will probably require its own Github action. Some things to keep in mind:
- Always having to download micromamba and install will be slower, than having it bundled in the `Github Worker`, but to make that happen mamba requires more adoption.
- Cache is a balance between how much time it takes to download, how much time it takes to zip the package cache and how much time it takes to unzip it, so there are cases were caching

I don't really see an advantage over bundled miniconda and just installing mamba from there. Am I missing something 🙃 ?

**Comment by adriangb** [comment]
I may be misunderstanding how this action works, but...

Currently this uses the bundled `miniconda` to download the latest `mamba`?

**Comment by goanpeca** [comment]
>Currently this uses the bundled miniconda to download the latest mamba? Are you saying that this will be faster than downloading micromamba directly, so there's no point in using micromamba?

Yep.

**Comment by adriangb** [comment]
That makes sense. So if I want the fastest installs, would the following be my best bet:

```yaml
     - name: Cache conda/mamba
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('test-env.yml') }}

      - name: Setup micromamba
        uses: goanpeca/setup-miniconda@v1
        with:
          channels: conda-forge
          activate-environment: test
          mamba-version: "*"
          use-only-tar-bz2: true  # requried for caching
          environment-file: test-env.yml

      - name: Show conda environment
        shell: bash -l {0}
        run: |
          mamba list
```
