### ISSUE TITLE
Getting deprecation warnings for "add-path" and "set-env"

### ISSUE THREAD

**Issue by uniqueg** [conda-incubator/setup-miniconda#78]
Thanks for the nice project! Seems to work rather nicely - except that apart from warnings regarding duplicate channels that have already been reported (#57), I'm also getting rather worrying warnings from GitHub Actions regarding the use of `add-path` and `set-env`:

```console
# Locating Miniconda...
#######################

/usr/share/miniconda

# Setup environment variables...
################################

Add "/usr/share/miniconda/condabin" to PATH
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
/usr/share/miniconda/condabin/conda config --add pkgs_dirs /home/runner/conda_pkgs_dir
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

My workflow config:
```yaml
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda environment with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v1.7.0
      with:
        activate-environment: install-deps
        auto-activate-base: false
        auto-update-conda: true
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
  # ... 
```

Apparently this is related to a mild security vulnerability and the deprecation warnings have only been added a couple of days ago. See this blog post for more info, including how to mitigate the issue: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
