### ISSUE TITLE
Setup conda step takes too long

### ISSUE THREAD

**Issue by ma-sadeghi** [conda-incubator/setup-miniconda#89]
Thank you for creating/maintaining this great Action!

It seems that setting up `conda` alone takes longer than usual. For example, take a look at this [log](https://github.com/PMEAL/OpenPNM/runs/1382060784?check_suite_focus=true), the "Set up conda" step. It takes 3 and a half minutes setting up conda (excluding the installation of dependencies). Is that expected or am I doing something wrong?

Thank you once again!

**Comment by goanpeca** [comment]
Hi @ma-sadeghi, thanks for the kind words and using the action :) 

>It seems that setting up conda alone takes longer than usual. 

Has this changed in any newer version? When did you notice started noticing this?

Just wondering so we can pinpoint to any potential issue.

**Comment by hadim** [comment]
Same issue for me using mamba (without installing my deps during the action) and with the latest v2 version.

**Comment by goanpeca** [comment]
@bollwyvl I could use hand debugging this

**Comment by hadim** [comment]
In case it helps (I can't share the logs):

```yaml
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          use-only-tar-bz2: true
```

**Comment by goanpeca** [comment]
Thanks @hadim for the example. Will add a PR to check the changes that introduced the regression.

**Comment by ma-sadeghi** [comment]
> Hi @ma-sadeghi, thanks for the kind words and for using the action :)
> 
> > It seems that setting up conda alone takes longer than usual.
> 
> Has this changed in any newer version? When did you notice started noticing this?
> 
> Just wondering so we can pinpoint to any potential issue.
> 
> @conda-incubator/setup-miniconda-team have you noticed anything similiar as described?

I'm almost sure that it used to be much quicker the first time I used this Action, off the top of my head, maybe it took 1 minute or so setting up conda, now it's at 3:30 minutes. Our project is public, and it's been a while since we're using this Action, so feel free to check out our logs in case that helps debugging the issue: https://github.com/PMEAL/OpenPNM/actions

**Comment by bollwyvl** [comment]
From the linked logs:
```
Tue, 10 Nov 2020 21:09:23 GMT /usr/share/miniconda/condabin/conda update conda
Tue, 10 Nov 2020 21:09:54 GMT Collecting package metadata (repodata.json): ...working... done
Tue, 10 Nov 2020 21:10:07 GMT Solving environment: ...working... done
Tue, 10 Nov 2020 21:11:56 GMT
Tue, 10 Nov 2020 21:11:56 GMT ## Package Plan ##
```
So we have, somewhat unscientifically:
- 26 seconds of getting repodata
- 135 seconds of doing the solve to update conda

The only thing I can think of is `conda-forge` being added, which puts the solver in over-drive with an extra 10k+ packages (and all their versions).

Some options, off the top of my head:
- in your repo...
  - set `auto-update-conda` to `false`
    - you'll kinda get what you get, but you'll _usually_ be fine
  - generate/check in [explicit specification](https://github.com/conda-incubator/setup-miniconda/blob/v2.0.0/README.md#example-7-explicit-specification) with [`conda-lock`](https://github.com/conda-incubator/conda-lock)
  - use a [custom installer](https://github.com/conda-incubator/setup-miniconda#example-5-custom-installer)
    - yeah, the download might take longer, but the solver won't get invoked
    - you can/should cache this as well, but sourcing one from github will be faster than going out to the internet 
- on _this_ repo..
  - add a new action option, which will only pull from a limited selection of channels, e.g. `conda-update-channels: defaults`
  - add some `::group::Boring stuff` `::endgroup::` log output so that top-level lifecycle of the commands this action runs are easier to track (i had to dust off my pandas to do some of the timing stuff)
    - haven't tried in anger... it _might_ 
  - offer a `micromaba` setup (again, saving a couple solves) https://github.com/conda-incubator/setup-miniconda/issues/75#issuecomment-698024879

**Comment by hadim** [comment]
For what it's worth most of the time is spent installing mamba:

![image](https://user-images.githubusercontent.com/528003/101086597-1850cf80-357f-11eb-8d7e-3a4c8c0f787f.png)

Is that possible to use something like micromamba instead of miniconda or miniforge?

**Comment by hadim** [comment]
Looking at the detail the solving step is what takes 99% of the time.

**Comment by jaimergp** [comment]
If [this issue ](https://github.com/conda-forge/miniforge/issues/23) gets addressed, the miniforge route will provide this by default :D

**Comment by hadim** [comment]
I confirm the recently released MambaForge installer makes the CI faster:

```yaml
- name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.9.2-2/Mambaforge-Linux-x86_64.sh
          channel-priority: true
          use-only-tar-bz2: true
          activate-environment: my-env

      - name: Anaconda Login
        run: |
          # Bypass the installation of anaconda-client
          TOKEN_DIR="$HOME/.config/binstar"
          TOKEN_PATH="$TOKEN_DIR/https%3A%2F%2Fapi.anaconda.org.token"
          mkdir -p $TOKEN_DIR
          echo -e "${ANACONDA_USER_TOKEN}\c" > $TOKEN_PATH

      - name: Install Dependencies
        run: mamba env update -f env.yml
```

(the snippet also includes a way to login to anaconda without the need to install `anaconda-client`. Could be helpful for some here.)
