### ISSUE TITLE
Use password and username instead of a token

### ISSUE THREAD

**Issue by hadim** [conda-incubator/setup-miniconda#90]
I use `anaconda login` instead of a token to access private packages. Could that be added as an option. Currently my setup looks like the following:

```yaml
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          use-only-tar-bz2: true
          activate-environment: my-env

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          mamba install -y anaconda-client
          yes 2>/dev/null | anaconda login --username $ANACONDA_USER  --password $ANACONDA_PASSWORD || true

          mamba env update -f env.yml
```

Would be nice and probably faster to do everything within the `conda-incubator/setup-miniconda` action:

```yaml
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          use-only-tar-bz2: true
          activate-environment: my-env
          anaconda_username: ${{ env.ANACONDA_USER }}
          anaconda_password: ${{ env.ANACONDA_PASSWORD }}
          environment-file: env.yml
```
