### ISSUE TITLE
Deprecation of `add-path` & `set-env` Breaking the Action

### ISSUE THREAD

**Issue by AyrtonB** [conda-incubator/setup-miniconda#91]
Thanks for this great resource! It's been working really well for me over the last couple of weeks but today I got an error relating to some steps in the action being deprecated by GitHub (below).

**Errors**
* The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env
* The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Any help/guidance would be much appreicated!

The behaviour can be replicated with this .yml
```
name: CI
on: [push, pull_request]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
            
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: true
      - shell: bash -l {0}
        run: |
          conda activate satip_dev
          pip install nbdev jupyter
          pip install -e .
          
      - name: Checking conda installs
        shell: bash -l {0}
        run: |
          conda activate satip_dev
          conda info
          conda list
```
